apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-model-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: python:3.9-slim
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_PATH
          value: "/models/model.json"
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        command: ["python", "-m", "http.server", "8080"]
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
