apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediation-controller
  template:
    metadata:
      labels:
        app: remediation-controller
    spec:
      serviceAccountName: default
      containers:
      - name: controller
        image: busybox
        command:
        - sh
        - -c
        - |
          while true; do
            echo "[$(date)] Checking system health..."
            
            # Simulate health check
            HEALTH_STATUS=$((RANDOM % 10))
            
            if [ $HEALTH_STATUS -lt 2 ]; then
              echo "[$(date)] Issue detected! Initiating remediation..."
              echo "[$(date)] Remediation action: Restarting unhealthy components"
              echo "[$(date)] Remediation completed successfully"
            else
              echo "[$(date)] System healthy - no action needed"
            fi
            
            sleep 30
          done
