apiVersion: batch/v1
kind: CronJob
metadata:
  name: drift-detector
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: drift-checker
            image: python:3.9-slim
            command:
            - python
            - -c
            - |
              import json
              import random
              
              # Simulate drift detection
              current_accuracy = 0.95 + random.uniform(-0.05, 0.05)
              baseline_accuracy = 0.95
              drift_threshold = 0.03
              
              drift = abs(current_accuracy - baseline_accuracy)
              
              result = {
                  "current_accuracy": current_accuracy,
                  "baseline_accuracy": baseline_accuracy,
                  "drift": drift,
                  "threshold": drift_threshold,
                  "drift_detected": drift > drift_threshold
              }
              
              print(json.dumps(result, indent=2))
              
              if result["drift_detected"]:
                  print("WARNING: Model drift detected!")
                  exit(1)
