kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31080
    hostPort: 8080
  - containerPort: 31090
    hostPort: 9000
  - containerPort: 31091
    hostPort: 9001
