apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
data:
  rules.yaml: |
    groups:
      - name: ml_model_alerts
        interval: 30s
        rules:
          - alert: ModelAccuracyLow
            expr: model_accuracy < 0.90
            for: 2m
            labels:
              severity: critical
              component: ml-model
            annotations:
              summary: "Model accuracy dropped below threshold"
              description: "Model {{ $labels.model }} accuracy is {{ $value }}"
          
          - alert: ModelLatencyHigh
            expr: model_latency_ms > 1000
            for: 1m
            labels:
              severity: warning
              component: ml-model
            annotations:
              summary: "Model latency is high"
              description: "Model {{ $labels.model }} latency is {{ $value }}ms"
          
          - alert: ModelErrorRateHigh
            expr: model_error_rate > 0.05
            for: 1m
            labels:
              severity: critical
              component: ml-model
            annotations:
              summary: "Model error rate is high"
              description: "Model {{ $labels.model }} error rate is {{ $value }}"
