apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-model-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: python:3.9-slim
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/model.pkl"
        command: 
        - python
        - -m
        - http.server
        - "8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
