apiVersion: v1
kind: Service
metadata:
  name: model-server
  labels:
    app: model-server
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
    name: http
  selector:
    app: model-server
