metrics:
  - name: model_accuracy
    type: gauge
  - name: prediction_latency
    type: histogram
  - name: request_count
    type: counter
alerts:
  - name: accuracy_degradation
    condition: "accuracy < 0.90"
  - name: high_latency
    condition: "p95_latency > 200ms"
