name: ML Pipeline

on:
  push:
    paths:
      - 'models/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow dvc pandas scikit-learn
    
    - name: Train model
      run: |
        python src/train_model.py
    
    - name: Run tests
      run: |
        python src/test_model.py
    
    - name: Upload model to MinIO
      run: |
        echo "Model uploaded to MinIO"
    
    - name: Deploy to Kubernetes
      run: |
        echo "Model deployed to Kubernetes"
